# Generated by Django 5.1.6 on 2025-03-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('distribution_expense', models.FloatField()),
                ('published_date', models.DateField()),
            ],
        ),
    ]
